#!/bin/sh

path='~/.diary'

dir=$1
if [ -z "$dir" ]
then
    dir=offline
fi

date_dir_=`date +'%Y/%m %B'`
date_dir="$path/$dir/$date_dir"
date_file=`date +'%d %A'`

mkdir -p "$date_dir"

win_date_file=`ls -t1 "$date_dir/$date_file.*" 2>/dev/null | head -1`

if [ ! -z "$win_date_file" ]
then
    date_file="$win_date_file"
fi

my editor "$date_dir/$date_file"
