#!/bin/sh

firstchar=`echo "$1" | cut -c 1`
secondchar=`echo "$1" | cut -c 2`
if [ "$firstchar" = "/" ] || [ "$secondchar" = "/" ]
then
    target="$1"
else
    target="$HOME/.exe/$1"
fi

if [ -w `dirname "$target"` ]
then
    prefix=
else
    prefix=sudo
fi

if [ ! -f "$target" ]
then
    newfile="/tmp/$RANDOM.exe"
    if [ -f ~/.config/exe_template ]
    then
        cp ~/.config/exe_template "$newfile"
    else
        touch "$newfile"
    fi
    chmod a+x "$newfile"
    $prefix mv "$newfile" "$target"
fi

editor="$HOME/bin/editor"
exec $prefix "$editor" "$target"
